name: Spring CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Java & Docker setting
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # SpringBoot application build
      - name: Build with Gradle without running tests
        run: |
          cd demo
          ./gradlew build -x test --no-daemon
        env:
          WEE_DB_URL: ${{ secrets.WEE_DB_URL }}
          WEE_DB_USERNAME: ${{ secrets.WEE_DB_USERNAME }}
          WEE_DB_PASSWORD: ${{ secrets.WEE_DB_PASSWORD }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          KAKAO_REDIRECT_URL: ${{ secrets.KAKAO_REDIRECT_URL }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          NAVER_REDIRECT_URL: ${{ secrets.NAVER_REDIRECT_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}

      # Docker hub login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker build & push
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./demo
          file: ./demo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:be


  CD:
    needs: [ CI ]
    runs-on: ubuntu-latest

    # The latest docker image pull & container run 
    steps:
      - name: Docker image pull and Container run
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            docker stop wee-was
            docker rm wee-was
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:be
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:be
            docker run -d -p 8080:8080 \
            -e WEE_DB_URL="${{ secrets.WEE_DB_URL }}" \
            -e WEE_DB_USERNAME="${{ secrets.WEE_DB_USERNAME }}" \
            -e WEE_DB_PASSWORD="${{ secrets.WEE_DB_PASSWORD }}" \
            -e KAKAO_CLIENT_ID="${{ secrets.KAKAO_CLIENT_ID }}" \
            -e KAKAO_CLIENT_SECRET="${{ secrets.KAKAO_CLIENT_SECRET }}" \
            -e KAKAO_REDIRECT_URL="${{ secrets.KAKAO_REDIRECT_URL }}" \
            -e NAVER_CLIENT_ID="${{ secrets.NAVER_CLIENT_ID }}" \
            -e NAVER_CLIENT_SECRET="${{ secrets.NAVER_CLIENT_SECRET }}" \
            -e NAVER_REDIRECT_URL="${{ secrets.NAVER_REDIRECT_URL }}" \
            -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            -e GOOGLE_REDIRECT_URL="${{ secrets.GOOGL_REDIRECT_URL }}" \
            --name wee-was ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:be

